name: main

on:
  push:
    branches:
      - main
  pull_request:


jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Install Tools
        run: make install_tools

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Run Tests
        run: make test

      - name: Run Integration
        run: |
          # go run ./cmd/server &
          # sleep 5
          curl --silent --insecure --fail --show-error --location http://127.0.0.1:8080/voyager > /dev/null
          kill -9 %1

  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build]
    timeout-minutes: 10
    steps:
      - name: Release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
