name: main

on:
  push:
    branches:
      - main
  pull_request:


jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Install Tools
        run: make install_tools

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Run Tests
        run: make test

  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Release
        uses: go-semantic-release/action@v1
        if: github.ref == 'refs/heads/main'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
